apiVersion: v2
name: tsbmp-compplete
description: A Helm chart for Kubernetes
version: 1.4.0
type: application

dependencies:
  - name: cert-manager
    repository: file://subcharts/cert-manager
    version: v1.5.3
    condition: cert-manager.enabled
  - name: eck-operator
    repository: file://subcharts/eck-operator
    version: 1.7.1
    condition: eck-operator.enabled
  - name: postgres-operator
    repository: file://subcharts/postgres-operator
    version: 1.6.3
    condition: postgres-operator.enabled
  - name: tsbmp
    repository: file://subcharts/tsbmp
    version: 1.3.0
    condition: tsbmp.enabled
